version: '3.8'

services:
  # Nodo de Laboratorio: Python y Herramientas de Red
  python-tester:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: vamp_python_lab
    env_file:
      - ./scripts/passive_recon/.env  # copy from .env.example
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    # NET_ADMIN required for ICMP tunnel and ARP tools
    cap_add:
      - NET_ADMIN
    network_mode: "bridge"
    working_dir: /app
